server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    #how long to wait before closing a TCP connection if not data is transferred
    idle-timeout: 15s
spring:
  application:
    name: order-service
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      #The maximum time to wait to get a connection from the pool
      max-create-connection-time: 2s
      #the initial size of the connection pool
      initial-size: 5
      #the maximum number of connections kept in the pool
      max-size: 10
  lifecycle:
    #Grace period
    timeout-per-shutdown-phase: 15s